### ISSUE TITLE
TraceRoute does not work with .NET MAUI Android App

### ISSUE THREAD

**Issue by norton287** [hekkaaa/NetObserver#40]
My .NET MAUI Android App (Targeting .NET 6) works great with your ping and ICMP utils but none of the Traceroute functions work on mobile devices (Phone or Tablet).  It is a closed-source project but I can share via email a link to a zip of it if you want to test it.

When running the various methods for Traceroute the List only contains one object which is the destination host object and none of the intermediate hosts at all.

If you want to run the project let me know and I'll give you my email address.

**Comment by hekkaaa** [comment]
Hi @norton287!
My library has not been tested on mobile devices. I was sure that .NET Standard 2.0 won't cause any problems.
Please specify which version of Android your app is designed for?
I will create a test project on MAUI and check the functionality myself first.

**Comment by norton287** [comment]
I have tested targeting .NET 6 with Android 12 and 13

**Comment by hekkaaa** [comment]
Okay, I will check it soon and give you an answer.

**Comment by hekkaaa** [comment]
Indeed, I see such a bug! I checked it on the Android 12 emulator.
Well, I will try to figure it out and eliminate it in the near future.
Perhaps ICMP works differently for mobile devices.

![image](https://user-images.githubusercontent.com/46771781/204141134-afdee172-fa17-4d92-b86b-d9ebce107881.png)

**Comment by norton287** [comment]
Not sure I downloaded 10 tracert apps from the app store and tested and they all worked fine.  I'm not sure if they were native Android or not but they worked well.

This was on both mobile and tablet.



From: Alexander Pototsky ***@***.***>***@***.***>
Reply: hekkaaa/NetObserver ***@***.***>***@***.***>
Date: November 27, 2022 at 8:42:00 AM
To: hekkaaa/NetObserver ***@***.***>***@***.***>
CC: John Norton ***@***.***>***@***.***>, Mention ***@***.***>***@***.***>
Subject:  Re: [hekkaaa/NetObserver] TraceRoute does not work with .NET MAUI Android App (Issue #40)


Indeed, I see such a bug! I checked it on the Android 12 emulator.
Well, I will try to figure it out and eliminate it in the near future.
Perhaps ICMP works differently for mobile devices.

[image]<https://user-images.githubusercontent.com/46771781/204141134-afdee172-fa17-4d92-b86b-d9ebce107881.png>

**Comment by hekkaaa** [comment]
Greetings @norton287 !
I partially figured out the problem.
The absence of data in the object is due to the incorrect operation of the android emulator dns server.
When I try to send an ICMP request directly, I get an empty object with the error - **System.Net.Sockets.SocketException exception: The operation is not supported on the transport endpoint**

![err_wi-fi](https://user-images.githubusercontent.com/46771781/204215883-74496127-8e45-47c7-b827-7cd17df1d39d.png)
![err_ping1](https://user-images.githubusercontent.com/46771781/204216019-e4818903-660c-47f9-b5af-5b7499f7aa48.png)

I checked the theory and the same code in the emulator and on a real device (Android 12) works differently.

**Emulator:**
![image](https://user-images.githubusercontent.com/46771781/204217134-3f70889a-d69b-407c-bef5-071547f5e38d.png)

**Real phone:**
![image](https://user-images.githubusercontent.com/46771781/204217571-519e2f77-c826-4e24-bdaa-b42c8791f63b.png)


![image](https://user-images.githubusercontent.com/46771781/204217780-0b594b10-280f-40a7-b44e-0d8cda87f6ea.png)

The only problem I see is that the entire route list should be output, but only the last ip address is output.
But this bug can be fixed only after solving the emulator problem.

**Summarizing**: The problem you are facing is presumably related to the work of DNS in Hyper-V. You need to understand how to configure the network correctly in emulation to work with ICMP packets.
If you can figure this out, I, for my part, will use your setup manual and check the operation of the tracing utility code.

Test APK files that I created and tested:
https://drive.google.com/file/d/10BYS7DCe1pFDVSSeHWm8bnTvt8h7v9BU/view?usp=share_link
https://drive.google.com/file/d/1xTWjX3MvdFLbxSLi5Twzbq3qizF8iKZI/view?usp=share_link

**Comment by norton287** [comment]
@hekkaaa This maybe due to a double NAT issue with the emulator and DNS.  I will start work on it today trying to get it resolving correctly.

John

**Comment by norton287** [comment]
@hekkaaa after some further testing with the emulator and with my physical device I tested with a Windows MAUI app and your package works excellently!  So it is not the package but something in Android or MAUI Android that is causing this issue, so I have opened this issue with the MAUI Android team [MAUI Issue](https://github.com/dotnet/runtime/issues/78990#issuecomment-1332202654).  So I think you can close this as your code is perfect as far as I am concerned!

**Comment by hekkaaa** [comment]
@norton287 
Thanks) I am pleased that you appreciated my code) It means a lot to me.

**Comment by norton287** [comment]
Your package really simplifies things and works very well! I'm glad I found it because it makes my life much easier.


On November 30, 2022 9:10:14 PM Alexander Pototsky ***@***.***> wrote:

@norton287<https://github.com/norton287>
Thanks) I am pleased that you appreciated my code) It means a lot to me.
